"""
Migration to create LeaveApplication model and delete LeaveRequest model.

This migration creates the LeaveApplication model and deletes the obsolete LeaveRequest model.
Generated by Django 4.2.6 on 2023-11-14 11:05.
"""

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    """
    Database migration to create LeaveApplication model and delete LeaveRequest model.
    """

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                    )
                    ),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(
                    choices=[
                        ('pending', 'Pending'),
                        ('approved', 'Approved'),
                        ('rejected', 'Rejected'),
                        ],
                    default='pending',
                    max_length=10
                )),
                ('reason', models.TextField()),
                ('processed_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='processed_leaves',
                    to=settings.AUTH_USER_MODEL
                )),
                ('requested_by', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='leave_requests',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
        ),
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
    ]
