# Generated by Django 4.2.6 on 2023-11-06 09:23

from django.db import migrations

def migrate_author_to_contributors(apps, schema_editor):
    Blog = apps.get_model('iga', 'Blog')
    for blog in Blog.objects.all():
        if blog.author:
            blog.contributors.add(
                blog.author, through_defaults={'contribution': 'Primary Author'})


class Migration(migrations.Migration):

    dependencies = [
        ('iga', '0003_alter_blog_options_alter_blog_author_blogcontributor_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_author_to_contributors)
    ]
