# Generated by Django 4.2.6 on 2023-11-06 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iga', '0004_auto_20231106_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
    ]
