# Generated by Django 4.2.6 on 2023-11-22 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iga', '0006_blog_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='contributors',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='language',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='word_count',
        ),
    ]
