# Generated by Django 4.2.6 on 2023-11-22 09:26

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iga', '0007_remove_blog_contributors_remove_blog_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='contributors',
            field=models.ManyToManyField(related_name='contributed_blogs', through='iga.BlogContributor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='blog',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('ki', 'kirundi')], default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='blog',
            name='word_count',
            field=models.IntegerField(null=True),
        ),
    ]
