# Generated by Django 4.2.6 on 2023-11-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iga', '0008_blog_contributors_blog_created_at_blog_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
