# Generated by Django 4.2.6 on 2023-11-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_user_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CREATOR', 'Creator'), ('FOLLOWER', 'Follower')], max_length=30),
        ),
    ]
