# Generated by Django 4.2.6 on 2023-11-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CREATOR', 'Creator'), ('FOLLOWER', 'Follower'), ('SUBSCRIBER', 'Subscriber')], max_length=30),
        ),
    ]
